### ISSUE TITLE
make error!!

### ISSUE THREAD

**Issue by JeffersonHuang** [SausageCode/Embedded_videos#1]
Hi, your video is very goog , it is of great help to me. I found your code on github, I tried to compile but the following prompt appeared, I tried to modify the Makfiel But is seems to have no effect.
```
make: *** No rule to make target 'system_stm32f4xx.c', needed by 'TEMPLATE.elf'.  Stop.
```

**Comment by JankingHuang** [comment]
I  am sorry ,I wrote the wrong path ‘STM_COMON’

**Comment by JeffersonHuang** [comment]
I am sorry ,I wrote the wrong path ‘STM_COMON’
