### ISSUE TITLE
i don't get usbd_hid .h/.c files when generating code

### ISSUE THREAD

**Issue by bedmonson85** [SausageCode/Embedded_videos#2]
When I generate code, I don't get a usbd_hid.h/.c file.  The closest thing to that name is a usbd_customhid.h/.c 
file under STM32_USB_Device_Library directory.  Did ST change their library code generation maybe? Or do I have something set up wrong.  I'm using STM32CubeIDE Version: 1.10.1 and I'm using a BluePill board with STM32f103C8T6.

![files](https://user-images.githubusercontent.com/6627592/196305662-a8428c18-3b9f-451f-a0d4-cdc7ca5a7f90.png)

**Comment by bedmonson85** [comment]
edit: I think the library has just changed the name of the usbd_customhid.h/.c files (shown in the video) to usbd_custom_hid.h/.c (what the IDE generates for me) at some point; they look pretty much the same to me.  I'm going to close this issue for now.

**Comment by prtzl** [comment]
Thank you for looking into this. I'll pin this issue so this might help someone else as well.
